cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views
app_name = 'coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

dsg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from . import views as v
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', v.contact, name='contact'),
    path('about/', v.about, name='about'),
    path('faq/', v.faq, name='faq'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
name='admin_order_detail'),
    path('management/', views.profile, name='profile'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='',
    choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs={'class':'cart-hide form-control'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.contrib.auth.decorators import login_required
from shop.recommender import Recommender
from coupons.forms import CouponApplyForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
@login_required
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')
@login_required
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    coupon_apply_form = CouponApplyForm() 
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products, max_results=4)
    print('Products:', recommended_products)
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form, 'recommended_products': recommended_products})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <div id="basket" class="col-lg-9">
              <div class="box">
              
                  <h1>Shopping cart</h1>
                  <p class="text-muted">You currently have {{cart.get_total_quantity}} item(s) in your cart.</p>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th colspan="2">Product</th>
                          <th>Quantity</th>
                          <th>Unit price</th>
                          <th>Discount</th>
                          <th colspan="2">Total</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for item in cart %}
                      {% with product=item.product %}
                        <tr>
                          <td><a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a></td>
                          <td><a href="#">{{product.name}}</a></td>
                          <td>
                           <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <button type="submit" class='btn btn-primary'>Update</button>
                            {% csrf_token %}
                            </form>
                          </td>
                          <td>${{item.price}}</td>
                          <td>{% if cart.coupon %}
                          -{{cart.coupon.discount}}%
                          {% else %}_
                          {% endif %}
                          </td>
                          <td>${{item.total_price}}</td>
                          <td><a href="#"><i class="fa fa-trash-o"></i></a></td>
                        </tr>
                      {% endwith %}
																					{% endfor %}
                      </tbody>
                      <tfoot>
                        <tr>
                          <th colspan="5">Sub Total</th>
                          <th colspan="2">${{cart.get_total_price}}</th>
                        </tr>
                      </tfoot>
                    </table>
                     <div class="box">
    <div class="box-header">
       <h4 class="mb-0">Coupon code
           {% if cart.coupon %}
           "{{cart.coupon.code}}" ({{cart.coupon.discount}}% off)
           
        </h4>
     </div>
     <h2>Total: ${{cart.get_total_price_after_discount|floatformat:'2'}}</h2>
     {% else %}
     <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
    <form method="post" action="{% url 'coupons:apply' %}">
     <div class="input-group">
      {{coupon_apply_form}}<span class="input-group-append">
       {% csrf_token %}
       <button type="submit" class="btn btn-primary"><i class="fa fa-gift"></i></button></span>
     </div>
     {% endif %}
     <!-- /input-group-->
    </form>
 </div>
                  </div>
                  <!-- /.table-responsive-->
                  <div class="box-footer d-flex justify-content-between flex-column flex-lg-row">
                    <div class="left"><a href="{% url 'shop:product_list' %}" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Continue shopping</a></div>
                    <div class="right">
                    
                      <a href="{% url 'orders:order_create' %}"><button class="btn btn-primary">Proceed to checkout <i class="fa fa-chevron-right"></i></button></a>
                    </div>
                  </div>
                
              </div>
              <!-- /.box-->
             {% if recommended_products %}
              <div class="row same-height-row">
                <div class="col-lg-3 col-md-6">
                  <div class="box same-height">
                    <h3>You may also like these products</h3>
                  </div>
                </div>
               {% for p in recommended_products %}
                <div class="col-md-3 col-sm-6">
                  <div class="product same-height">
                    <div class="flip-container">
                      <div class="flipper">
                        <div class="front"><a href="{{p.get_absolute_url}}"><img src="{{p.image.url}}" alt="{{p.name}}" class="img-fluid"></a></div>
                        <div class="back"><a href="{{p.get_absolute_url}}"><img src="{{p.image.url}}" alt="{{p.name}}" class="img-fluid"></a></div>
                      </div>
                    </div><a href="{{p.get_absolute_url}}" class="invisible"><img src="{{p.image.url}}" alt="" class="img-fluid"></a>
                    <div class="text">
                      <h3>{{p.name}}</h3>
                      <p class="price">${{p.price}}</p>
                    </div>
                  </div>
                  <!-- /.product-->
                </div>
                {% endfor %}
              </div>
            {% endif %}
            <!-- /.col-lg-9-->
           
            <!-- /.col-md-3-->
          </div>
        </div>
      </div>
    </div>
{% endblock %}