blog/urls.py
from .feeds import LatestPostsFeed
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

dsg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from . import views as v
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', v.contact, name='contact'),
    path('about/', v.about, name='about'),
    path('faq/', v.faq, name='faq'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.urls import reverse
from taggit.managers import TaggableManager
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                      .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    image = models.FileField(upload_to="post_images/%Y/%m/%d", blank=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

class Reply(models.Model):
    comment = models.ForeignKey(Post, related_name='replies', on_delete=models.CASCADE)
    body = models.CharField(max_length=500)
    user = models.ForeignKey(User, related_name='comment_replies', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Reply by {} to {}'.format(self.user.username, self.comment)

blog/forms.py
from django import forms
from .models import Comment, Reply

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Comment
        fields = ('body',)

class ReplyForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Reply
        fields = ('body',)

blog/views.py
from django.db.models import Count
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, ReplyForm
from taggit.models import Tag

def post_share(request, post_id):
    sent = False
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent':sent})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.user = request.user
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
    .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
    .order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts})

blog/templates/blog/post/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{post.title}}
{% endblock %}
{% block content %}
 <div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <div id="blog-post" class="col-lg-9">
              <div class="box">
                <h1>{{post.title}}</h1>
                <p class="author-date"><a href="#">{{post.author|capfirst}}</a> |  {{post.publish}} | <a href="{% url 'blog:post_share' post.id %}"><i class="fa fa-envelope"></i></a></p>
               <p class="tags">Tags: {{ post.tags.all|join:", " }}</p><hr> 
               <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
                <div id="post-content">
                  <p>{{post.body|linebreaks}}</p>
                  <blockquote class="blockquote">
                    <p>{{post.body|linebreaks}}</p>
                  </blockquote>
                 
                <!-- /#post-content-->
                <div id="comments">
                  <h4>{{comments.count}} comment{{comments.count|pluralize}}</h4>
                 
                 <div class="row comment">
                   {% for comment in comments %}
                    <div class="col-md-9 col-lg-10">
                      <p class="posted">{{comment.user.username|capfirst}} | <i class="fa fa-clock-o"></i> {{comment.created|timesince}}</p>
                       <div style="color:white;width:75%;height:auto;background:grey;border-radius:25px;padding:10px"><p>{{comment.body|linebreaks}}</p></div>
                      {% include 'blog/reply.html' %}
                    </div>
                    {% empty %}
                     No comments
                     {% endfor %}
                  </div>
                 
                  <!-- /.comment-->
                </div>
                <!-- /#comments-->
                <div id="comment-form">
                 {% if new_comment %}
                  <h2>Your comment has been added.</h2>
                  {% else %}
                 <h4>Leave comment</h4>
                  <form method="post" action=".">    
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          {{comment_form.body}}
                        </div>
                      </div>
                   </div>{% csrf_token %}
                    <div class="row">
                      <div class="col-md-12 text-right">
                        <button class="btn btn-primary" type="submit"><i class="fa fa-comment-o"></i> Post comment</button>
                      </div>
                    </div>
                  </form>
                 {% endif %}
                </div>
                <!-- /#comment-form-->
              </div>
              <!-- /.box-->
            </div>
            <!-- /#blog-post-->
            <div class="col-lg-3">
             
              <!-- /.col-lg-3-->
              <!-- *** BLOG MENU END ***-->
           <h2>Similar posts</h2>
{% for post in similar_posts %}
<div class="post">
                <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
                <p class="author-category"><a href="#">{{post.author|capfirst}}</a></p>
                <hr>
                <p class="date-comments"><a href="{{post.get_absolute_url}}"><i class="fa fa-calendar-o"></i> {{post.created}}</a><a href="{{post.get_absolute_url}}"><i class="fa fa-comment-o"></i> {{post.comments.count}} Comment{{post.comments.count|pluralize}}</a></p>
                <div class="image"><a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"></a></div>
                <p class="intro">{{post.body}}</p>
                <p class="read-more"><a href="{{post.get_absolute_url}}" class="btn btn-primary">Continue reading</a></p>
              </div>
{% empty %}
There are no similar posts yet.
{% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

blog/templates/blog/post/latest_posts.html
{% for post in latest_posts %}
<div class="col-sm-6">
                <div class="post">
                  <h4><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h4>
                  <p class="author-category">{{post.author.username|capfirst}}</a> <a href="">
                      {% for tag in post.tags.all %}
                      <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                       {% if not forloop.last %}, {% endif %}
                       {% endfor %} 
                      </p>
                  <hr>
                  <p><img src="{{post.image.url}}" class="img-fluid" alt="{{post.title}}"></p>
                  <p class="intro">{{post.body}}</p>
                  <p class="read-more"><a href="{{post.get_absolute_url}}" class="btn btn-primary">Continue reading</a></p>
                </div>
              </div>
{% endfor %}

blog/templates/blog/post/list.html
{% extends "shop/base.html" %}
{% load dsg %}
{% load static %}
{% block title %}
{% for p in posts %}
{{p.title}}
{% endfor %}
{% endblock %}
{% block content %}
<div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <!--
            *** LEFT COLUMN ***
            _________________________________________________________
            -->
            <div id="blog-listing" class="col-lg-9">
             <h2>Posts Available ({% total_posts %})</h2>               
              <!--<p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>-->
              <h3>Latest posts</h3>
              {% show_latest_posts 3 %}
              {% if tag %}
               <h2>Posts tagged with "{{ tag.name }}"</h2>
              {% endif %}
              {% for post in posts %}
               <!--<h3>Most commented posts</h3>
              {% get_most_commented_posts as most_commented_posts %}
              <ul>
              {% for post in most_commented_posts %}
              <li>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </li>
              {% endfor %}
              </ul>-->
              <!-- post-->
              <div class="post">
                <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
                <p class="author-category"><a href="#">{{post.author|capfirst}}</a><hr><a href=""><p class="tags">Tags:
{% for tag in post.tags.all %}
<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
{{ tag.name }}
</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}</p></a></p>
                <hr>
                <p class="date-comments"><a href="{{post.get_absolute_url}}"><i class="fa fa-calendar-o"></i> {{post.publish}}</a><a href="{{post.get_absolute_url}}"><i class="fa fa-comment-o"></i> {{post.comments.count}} Comment{{post.comments.count|pluralize}}</a></p>
                <div class="image"><a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"></a></div>
                <p class="intro">{{post.body|truncatewords:30|linebreaks}}</p>
                <p class="read-more"><a href="{{post.get_absolute_url}}" class="btn btn-primary">Continue reading</a></p>
              </div>
              <!-- post -->
                {% endfor %}
           {% include "pagination.html" with page=posts %}
            </div>
            <!-- /.col-lg-9-->
            <!-- *** LEFT COLUMN END ***-->
            
            <div class="col-lg-3">
              <!--
              *** BLOG MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu mb-4">
                <div class="card-header">
                  <h3 class="h4 panel-title">Blog</h3>
                </div>
                <div class="card-body">
                  <ul class="nav flex-column nav-pills">
                    <li><a href="blog.html" class="nav-link">About us</a></li>
                    <li><a href="blog.html" class="nav-link active">Fashion</a></li>
                    <li><a href="blog.html" class="nav-link">News and gossip</a></li>
                    <li><a href="blog.html" class="nav-link">Design</a></li>
                  </ul>
                </div>
              </div>
              <!-- /.col-lg-3-->
              <!-- *** BLOG MENU END ***-->
              
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "shop/base.html" %}
{% block title %}Share a post {{post.title}}{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}