blog/urls.py
from .feeds import LatestPostsFeed
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

dsg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from . import views as v
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', v.contact, name='contact'),
    path('about/', v.about, name='about'),
    path('faq/', v.faq, name='faq'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.shortcuts import reverse
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

        def __str__(self):
            return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.FileField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/forms.py
from django import forms

class ContactForm(forms.Form):
    fname = forms.CharField(label='First Name', widget=forms.TextInput(attrs={'class':'form-control'}), required=False)
    lname = forms.CharField(label='Last Name', widget=forms.TextInput(attrs={'class':'form-control'}), required=False)
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class':'form-control'}), required=False)
    subject = forms.CharField(label='Subiect', widget=forms.TextInput(attrs={'class':'form-control'}), required=False)
    message = forms.CharField(label='Message', widget=forms.Textarea(attrs={'class':'form-control'}), required=False)

shop/views.py
from .recommender import Recommender
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Product
from cart.forms import CartAddProductForm
from .forms import ContactForm
from django.core.mail import send_mail

def index(request):
    return render(request, 'shop/index.html',{})

def contact(request):
    sent = False
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = "DSG {}".format(cd['subject'])
            message = "DSG Support request from {} {}({})\n\n{}\n DSG Contact Form".format(cd['fname'], cd['lname'], cd['email'], cd['message'])
            send_mail(subject, message, 'noreply@deut818systems.com', 'contact@deut818systems.com')
            form.save()
            sent = True
    return render(request, 'shop/contact.html', {'form':form, 'sent':sent})

def about(request):
    return render(request, 'shop/about.html', {})

def privacy(request):
    return render(request, 'shop/privacy.html', {})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    sort_10 = Product.objects.filter(available=True)[:10]
    sort_25 = Product.objects.filter(available=True)[:25]
    sort_50 = Product.objects.filter(available=True)[:50]
    sort_100 = Product.objects.filter(available=True)[:100]
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 10)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'products': products, 'cart_product_form': cart_product_form})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form, 'recommended_products':recommended_products, 'sort_10':sort_10, 'sort_25':sort_25, 'sort_50':sort_50, 'sort_100':sort_100})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Deut818 Systems Group{% endblock %}</title>
    <meta name="description" content="Deut818 Systems (U) is the operational arm of Alp Systems HB(Sweden) whose main goal is to promote and implement technological transfer projects in Africa through partnerships with other European based companies with intrest in investing in Africa. The major areas of intrest include Integrated Systems, Sustainable Solutions, Transport and Logistics, Security surveillance, Access control, data analytics, Biometrics,forensics and facial recognition, tourism and infrastructure development.">
    <meta name="keyword" content="transport">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    {% include 'shop/css.html' %}
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
      {% include 'shop/nav.html' %}
      {% block content %}
      {% endblock %}
      {% include 'shop/footer.html' %}
      {% include 'shop/scripts.html' %}
      {% block script %}
      {% endblock %}
  </body>
</html>

shop/templates/shop/contact.html
{% extends 'shop/base.html' %}
{% load dsg static %}
{% block title %}
Contact Us
{% endblock %}
{% block content %}
<div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
          
            <div class="col-lg-3">
              <!--
              *** PAGES MENU ***
              _________________________________________________________
              -->
              <div class="card sidebar-menu mb-4">
              </div>
              <!-- *** PAGES MENU END ***-->
              <div class="banner"><a href="#"><img src="{% static 'shop/img/banner.jpg' %}" alt="" class="img-fluid"></a></div>
            </div>
            <div class="col-lg-9">
              <div id="contact" class="box">
               <h1>Contact</h1>
                <p class="lead">Are you curious about something? Do you have some kind of problem with our products?</p>
                <p>Please feel free to contact us, our customer service center is working for you 24/7.</p>
                <hr>
                <div class="row">
                  <div class="col-md-4">
                    <h3><i class="fa fa-map-marker"></i>Address</h3>
                    <p>Deut818 Systems Group<br>Eco Building, Ndejje<br>Rubeire Rd.<br>P.O.Box 42 Kampala<br><strong>Uganda</strong></p>
                  </div>
                  <!-- /.col-sm-4-->
                  <div class="col-md-4">
                    <h3><i class="fa fa-phone"></i> Call center</h3>
                    <p class="text-muted">These numbers are not toll free, Standard charges May Apply</p>
                    <p><strong><a href="tel:+256703777625">+256 703 777 625</a><br><a href="tel:+447307294283">+44 7307 294283</a></strong></p>
                  </div>
                   <div class="col-md-4">
                    <h3><i class="fa fa-whatsapp"></i> WhatsApp</h3>
                    <p class="text-muted">Send us a message via WhatsApp</p>
                    <p><strong><a href="tel:+256703777625">+256 703 777 625</a><br><a href="tel:+447307294283">+44 7307 294283</a></strong></p>
                  </div>
                  <!-- /.col-sm-4-->
                  <div class="col-md-4">
                    <h3><i class="fa fa-envelope"></i> Email support</h3>
                    <p class="text-muted">Please feel free to write an email to us for support.</p>
                    <ul>
                      <li><strong><a href="mailto:info@deut818systems.com">info@deut818systems.com</a></strong></li>
                      <li><strong><a href="mailto:support@deut818systems.com">support@deut818systems.com</a></strong></li>
                    </ul>
                  </div>
                  <!-- /.col-sm-4-->
                </div>
                <!-- /.row-->
                <hr>
                <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.7793061924035!2d32.56887921399551!3d0.25338009981513604!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x177dbd62b50db41d%3A0x2395a31ca3fbc8df!2sDeut818%20Systems%20Group!5e0!3m2!1sen!2sbe!4v1570637235276!5m2!1sen!2sbe" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
	        </div>
                <hr>
                {% if sent %}
                <h2> Message sent, please check your email inbox for reply in the next 24hours</h2>
                {% else %}
                <h2>Contact form</h2>
                <form method="post" action=".">  
                   <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        {{form.fname.label_tag}}
                          {{form.fname}}
                          </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        {{form.lname.label_tag}}
                          {{form.lname}}
                          </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        {{form.email.label_tag}}
                          {{form.email}}
                          </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        {{form.subject.label_tag}}
                          {{form.subject}}
                          </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                     {{form.message.label_tag}}
                      {{form.message}}
                      </div>
                    </div>
                        {% csrf_token %}
                    <div class="col-md-12 text-center">
                      <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send message</button>
                    </div>
                    
                  </div>
                  <!-- /.row-->
                </form>
             {% endif %} 
              </div>
            </div>
            <!-- /.col-md-9-->
            
          </div>
        </div>
      </div>
    </div>
{% endblock %}

shop/templates/shop/css.html
 <!-- Bootstrap CSS-->
    {% load static %}  
    <link rel="stylesheet" href="{% static 'shop/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'shop/vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700">
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static 'shop/vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'shop/vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'shop/css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'shop/css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'shop/favicon.png' %}">
   

shop/templates/shop/footer.html
<div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Pages</h4>
            <ul class="list-unstyled">
              <li><a href="/about">About us</a></li>
              <li><a href="/terms">Terms and conditions</a></li>
              <li><a href="/faq">FAQ (Frequently Asked Questions)</a></li>
              <li><a href="/contact">Contact us</a></li>
            </ul>
            <hr>
            <h4 class="mb-3">User section</h4>
            <ul class="list-unstyled">
              <li><a href="/accounts/login">Login</a></li>
              <li><a href="{% url 'register' %}">Register</a></li>
            </ul>
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Where to find us</h4>
            <p><strong>Deut818 Systems Group</strong><br>P.O.Box 42<br>Kampala <strong>Uganda</strong><br><br>Ndejje, Rubeire rd<br></p><a href="/contact">Go to contact page</a>
            <hr class="d-block d-md-none">
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            
            <hr>
            <h4 class="mb-3">Stay in touch</h4>
            <p class="social"><a href="#" class="facebook external"><i class="fa fa-facebook"></i></a><a href="#" class="twitter external"><i class="fa fa-twitter"></i></a><a href="#" class="instagram external"><i class="fa fa-instagram"></i></a><a href="#" class="gplus external"><i class="fa fa-google-plus"></i></a><a href="#" class="email external"><i class="fa fa-envelope"></i></a></p>
          </div>
          <!-- /.col-lg-3-->
        </div>
        <!-- /.row-->
      </div>
      <!-- /.container-->
    </div>
 <div id="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-2 mb-lg-0">
            <p class="text-center text-lg-left">©2012-<span id="dt"></span> Deut818 Systems Group.</p>
          </div>
          <div class="col-lg-6">
            <p class="text-center text-lg-right">Developed by <a href="mailto:admin@deut818systems.com">DSG WebAdmin</a>
            </p>
          </div>
        </div>
      </div>
    </div>
<script>
var d = new Date();
document.getElementById("dt").innerHTML = d.getFullYear();
</script>

shop/templates/shop/modal.html
 <div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Customer login</h5>
                <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
              </div>
              <div class="modal-body">
                    {% if msg %}
                    <h4 class="text-danger">{{msg}}</h4>
                    {% endif %}
                <form action="." method="post">
                  <div class="form-group">
                    {{modal_form.username.label_tag}}
                    {{modal_form.username}}
                  </div>
                  <div class="form-group">
                    {{modal_form.password.label_tag}}
                    {{modal_form.password}}
                     {% csrf_token %}
                      </div>
                  <p class="text-center">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                  </p>
                </form>
                <p class="text-center text-muted">Not registered yet?</p>
                <p class="text-center text-muted"><a href="register.html"><strong>Register now</strong></a>! It is easy and done in 1 minute and gives you access to special discounts and much more!</p>
              </div>
            </div>
          </div>
        </div>

shop/templates/shop/nav.html
<!-- navbar-->
    <header class="header mb-5">
      <div id="top" style="margin-top:50px;">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 text-center text-lg-right">
              <ul class="menu list-inline mb-0">
   		{% if request.user.is_authenticated %}
		<li class="list-inline-item"><a href="/profile">Welcome {{request.user.username|capfirst}}</a></li>
                <li class="list-inline-item"><a href="/orders/management">Your Orders</a></li>
                <li class="list-inline-item"><a href="/accounts/logout">Logout</a></li>
 		{% else %}
                <li class="list-inline-item"><a href="{% url 'login' %}">Login</a></li>
                <li class="list-inline-item"><a href="{% url 'register' %}">Register</a></li>
 		{% endif %}
                <li class="list-inline-item"><a href="/contact">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
        {% load static %}
        
      </div>
      <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container"><a href="/" class="navbar-brand home"><img src="{% static 'shop/img/dsg.jpg' %}" alt="DSG logo" class="d-none d-md-inline-block"><img src="{% static 'shop/img/dsg.jpg' %}" alt="DSG logo" class="d-inline-block d-md-none" width='100px' height='40px'><span class="sr-only">DSG - go to homepage</span></a>
          <div class="navbar-buttons">
            <button type="button" data-toggle="collapse" data-target="#navigation" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
            <button type="button" data-toggle="collapse" data-target="#search" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></button><a href="{% url 'cart:cart_detail' %}" class="btn btn-outline-secondary navbar-toggler"><i class="fa fa-shopping-cart"></i><span class='badge'>{{cart.get_total_quantity}}</span></a>
          </div>
          <div id="navigation" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a href="{% url 'shop:index' %}" class="nav-link active">Home</a></li>
               <li class="nav-item dropdown menu-large"><a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">Shop<b class="caret"></b></a>
                <ul class="dropdown-menu megamenu">
                  <li>
                    <div class="row">
                      <div class="col-md-6 col-lg-3">
                        <h5>Products & Account</h5>
                        <ul class="list-unstyled mb-3">
                         
                            <li class="nav-item"><a href="{% url 'shop:product_list' %}" class="nav-link">Products</a></li>
                             <li class="nav-item"><a href="/orders/management" class="nav-link">Profile(Orders and Payments)</a></li>
                             <li class="nav-item"><a href="{% url 'password_change' %}" class="nav-link">Change Password</a></li>
                        
                         </ul>
                      </div>
                     
                    </div>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown menu-large"><a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">Blog<b class="caret"></b></a>
                <ul class="dropdown-menu megamenu">
                  <li>
                    <div class="row">
                      <div class="col-md-6 col-lg-3">
                        <h5>Blog Posts & News</h5>
                        <ul class="list-unstyled mb-3">
                            <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link">Posts</a></li>
                          </ul>
                      </div>
                    </div>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown menu-large"><a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">Info<b class="caret"></b></a>
                <ul class="dropdown-menu megamenu">
                  <li>
                    <div class="row">
                      <div class="col-md-6 col-lg-3">
                        <h5>Find Us</h5>
                        <ul class="list-unstyled mb-3">
                          <li class="nav-item"><a href="/contact" class="nav-link">Contact</a></li>
                          <li class="nav-item"><a href="/about" class="nav-link">About</a></li>
                          
                          <li class="nav-item"><a href="/faq" class="nav-link">FAQ (Frequently Asked Questions)</a></li>
                          <li class="nav-item"><a href="/privacy" class="nav-link">Privacy Policy</a></li>
                        </ul>
                      </div>
                    
                    </div>
                 </li>
                </ul>
              </li>
            </ul>
            <div class="navbar-buttons d-flex justify-content-end">
              <!-- /.nav-collapse-->
              <div id="search-not-mobile" class="navbar-collapse collapse"></div><a data-toggle="collapse" href="#search" class="btn navbar-btn btn-primary d-none d-lg-inline-block"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></a>
              {% with total_items=cart|length %}
              <div id="basket-overview" class="navbar-collapse collapse d-none d-lg-block"><a href="{% url 'cart:cart_detail' %}" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span class='badge'>{{total_items}}</span><span>{{total_items}} items in cart</span></a></div>
              {% endwith %}
            </div>
          </div>
        </div>
      </nav>
      <div id="search" class="collapse">
        <div class="container">
          <form role="search" class="ml-auto" action=".">
            <div class="input-group">
              {{search.q}}
                {% csrf_token %}
              <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </header>

shop/templates/shop/pager.html
<div class="pager d-flex justify-content-between" style="width:100%;">
   {% if page.has_previous %}
    <div class="previous"><a href="?page={{ page.previous_page_number }}" class="btn btn-outline-primary">← Prev</a></div>
  {% else %}
    <div class="previous disabled"><a href="javascript:void()" class="btn btn-outline-secondary disabled">← Prev</a></div>
   {% endif %}
    <div class="current" style="width:25%;background:white;height:38px;border-radius:25px;border:1px solid red;font-size:17px;color:gray;">
    <center>{{ page.number }} <span style="color:black;font-size:25px;">|</span> {{ page.paginator.num_pages }}</center>
    </div>
    {% if page.has_next %}
    <div class="next"><a href="?page={{ page.next_page_number }}" class="btn btn-outline-primary">Next →        </a></div>
    {% else %}
    <div class="next disabled"><a href="javscript:void" class="btn btn-outline-secondary disabled">Next →        </a></div>
    {% endif %}
</div>

shop/templates/shop/scripts.html
<!-- JavaScript files-->
    {% load static %}
    <script src="{% static 'shop/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'shop/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'shop/vendor/jquery.cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'shop/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'shop/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js' %}"></script>
    <script src="{% static 'shop/js/front.js' %}"></script>